"use client";

import { AIAnalyze } from "@/components/voicekeeper/fingerprint/ai-analyze";
import { FingerprintPreview } from "@/components/voicekeeper/fingerprint/fingerprint-preview";
import { FingerprintHeader } from "@/components/voicekeeper/fingerprint/header";
import { SystemPromptEditor } from "@/components/voicekeeper/fingerprint/system-prompt-editor";
import { useAuth } from "@/features/auth";
import { analyzeStyle, defaultStyleProfile, generateSystemPrompt, getApiKey, getFingerprint, isLegacyProfile, migrateLegacyProfile, setFingerprint, type StyleProfile } from "@/features/voicekeeper/fingerprint";
import { toast, EmptyState } from "@/ui";
import { useEffect, useMemo, useState } from "react";

export default function FingerprintPage() {
  const { user } = useAuth();
  const [textToAnalyze, setTextToAnalyze] = useState("");
  const [isAnalyzing, setIsAnalyzing] = useState(false);
  const [hasFingerprint, setHasFingerprint] = useState(false);
  const [hasApiKey, setHasApiKey] = useState(false);
  const [systemPrompt, setSystemPrompt] = useState("");
  
  const [styleProfile, setStyleProfile] = useState<StyleProfile>(defaultStyleProfile);

  // Автоматически генерируем system prompt при изменении профиля
  const autoGeneratedPrompt = useMemo(() => {
    return generateSystemPrompt(styleProfile);
  }, [styleProfile]);

  // Используем ручной промпт, если он задан, иначе автогенерированный
  useEffect(() => {
    if (!systemPrompt || systemPrompt === autoGeneratedPrompt) {
      setSystemPrompt(autoGeneratedPrompt);
    }
  }, [autoGeneratedPrompt]);

  // Load saved fingerprint and check API key
  useEffect(() => {
    if (!user?.id) return;
    const loadData = async () => {
      try {
        const saved = await getFingerprint(user.id);
        if (saved) {
          // Миграция legacy профилей
          if (isLegacyProfile(saved)) {
            const migrated = migrateLegacyProfile(saved);
            setStyleProfile(migrated);
            // Сохраняем мигрированный профиль
            await setFingerprint(migrated, user.id);
          } else {
            setStyleProfile(saved);
          }
          setHasFingerprint(true);
        }
        const apiKey = await getApiKey("gemini", user.id);
        setHasApiKey(!!apiKey);
      } catch (error) {
        console.error("Failed to load fingerprint/API key:", error);
      }
    };
    loadData();
  }, [user?.id]);

  const handleAnalyzeText = async () => {
    if (!textToAnalyze.trim() || textToAnalyze.length < 100) {
      toast({ title: "Добавьте минимум 100 символов текста", variant: "destructive" });
      return;
    }

    if (!hasApiKey) {
      toast({ 
        title: "API ключ не настроен", 
        description: "Перейдите в Настройки → API ключи",
        variant: "destructive" 
      });
      return;
    }

    setIsAnalyzing(true);
    
    try {
      if (!user?.id) {
        toast({ title: "Ошибка", description: "Пользователь не найден", variant: "destructive" });
        return;
      }
      const profile = await analyzeStyle(textToAnalyze, user.id);
      setStyleProfile(profile);
      await setFingerprint(profile, user.id);
      setHasFingerprint(true);
      toast({ title: "Стиль проанализирован!", variant: "success" });
    } catch (error) {
      toast({ 
        title: "Ошибка анализа", 
        description: error instanceof Error ? error.message : "Попробуйте позже",
        variant: "destructive" 
      });
    } finally {
      setIsAnalyzing(false);
    }
  };

  const handleSatisfactionChange = async (satisfaction: "like" | "dislike" | null) => {
    const updated = { ...styleProfile, satisfaction };
    setStyleProfile(updated);
    if (user?.id) {
      try {
        await setFingerprint(updated, user.id);
      } catch (error) {
        console.error("Failed to save satisfaction:", error);
      }
    }
  };

  const handleSave = async () => {
    try {
      if (!user?.id) {
        toast({ title: "Ошибка", description: "Пользователь не найден", variant: "destructive" });
        return;
      }
      // Сохраняем профиль с обновленным system prompt
      const updated = { ...styleProfile, systemPrompt };
      await setFingerprint(updated, user.id);
      setHasFingerprint(true);
      toast({ title: "Профиль сохранён", variant: "success" });
    } catch (error) {
      toast({ 
        title: "Ошибка сохранения", 
        description: error instanceof Error ? error.message : "Попробуйте позже",
        variant: "destructive" 
      });
    }
  };

  return (
    <div className="space-y-1.5">
      {/* Header */}
      <FingerprintHeader hasFingerprint={hasFingerprint} hasApiKey={hasApiKey} />

      {/* Main Content Grid */}
      <div className="grid gap-1.5 grid-cols-1 lg:grid-cols-12">
        {/* Left Column: AI Analyze and System Prompt */}
        <div className="lg:col-span-8 space-y-1.5">
          <AIAnalyze
            textToAnalyze={textToAnalyze}
            onTextChange={setTextToAnalyze}
            onAnalyze={handleAnalyzeText}
            isAnalyzing={isAnalyzing}
            hasApiKey={hasApiKey}
          />

          <SystemPromptEditor
            profile={styleProfile}
            systemPrompt={systemPrompt}
            onSystemPromptChange={setSystemPrompt}
          />
        </div>

        {/* Right Column: Fingerprint Preview */}
        <div className="lg:col-span-4">
          {hasFingerprint ? (
            <FingerprintPreview
              profile={styleProfile}
              onSatisfactionChange={handleSatisfactionChange}
              onSave={handleSave}
            />
          ) : (
            <EmptyState
              icon={null}
              title="Проанализируйте стиль"
              description="чтобы увидеть предпросмотр"
              variant="placeholder"
            />
          )}
        </div>
      </div>
    </div>
  );
}
